### ISSUE TITLE
Tool won't run

### ISSUE THREAD

**Issue by ulwur** [Beercow/SEPparser#4]
Hi!

I needed to parse some SEP logfiles that was sent to me, and tried to use your tool. But It won't even start..
What am I doing wrong?

C:\UnBackedUp_Data>python SepParser.py -h
Traceback (most recent call last):
  File "SepParser.py", line 471, in <module>
    vbnstruct.load(VBN_DEF)
  File "C:\WinPython-64bit-3.7.4.1\python-3.7.4.amd64\lib\site-packages\dissect\cstruct\cstruct.py", line 147, in load
    TokenParser(self, **kwargs).parse(definition)
  File "C:\WinPython-64bit-3.7.4.1\python-3.7.4.amd64\lib\site-packages\dissect\cstruct\parser.py", line 329, in parse
    self._typedef(tokens)
  File "C:\WinPython-64bit-3.7.4.1\python-3.7.4.amd64\lib\site-packages\dissect\cstruct\parser.py", line 143, in _typedef
    type_ = self._struct(tokens, register=True)
  File "C:\WinPython-64bit-3.7.4.1\python-3.7.4.amd64\lib\site-packages\dissect\cstruct\parser.py", line 174, in _struct
    field = self._parse_field(tokens)
  File "C:\WinPython-64bit-3.7.4.1\python-3.7.4.amd64\lib\site-packages\dissect\cstruct\parser.py", line 230, in _parse_field
    raise ParserError("line {:d}: expected name".format(self._lineno(tokens.next)))
dissect.cstruct.exceptions.ParserError: line 132: expected name

**Comment by Beercow** [comment]
Are you using the master or the dev branch?

**Comment by Beercow** [comment]
Figured out the problem. You need to use dissect.cstrict=1.0.0

I’ll have to figure out what is going on with 2.0

**Comment by Beercow** [comment]
Fixed 4e4e9d0f5b6260089363703a0dceddcdd25b9949

**Comment by ulwur** [comment]
Thanks! Outstanding!
